---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-storage
  namespace: local-path-storage
spec:
  chart:
    spec:
      chart: local-path-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner-charts
        namespace: flux-system
      version: 0.0.24-dev
  interval: 1m0s
  targetNamespace: local-path-storage
